/**
 * Builds a 200+ row CSV of REAL, publicly known business leaders at REAL companies
 * for testing AI person/company verification.
 *
 * Sources: public Fortune/company leadership disclosures and widely reported exec roles.
 * NOT scraped from LinkedIn. Phones and emails are synthetic. Do not contact anyone.
 *
 * Run: npx tsx scripts/generatePublicFiguresCsv.ts
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

type Person = {
  name: string;
  company: string;
  title: string;
};

/** Deduped public figures — names + companies from public leadership / news. */
const PEOPLE: Person[] = [
  // Fortune / large-cap CEOs (publicly disclosed)
  { name: "Doug McMillon", company: "Walmart", title: "President and CEO" },
  { name: "Andy Jassy", company: "Amazon", title: "President and CEO" },
  { name: "Andrew Witty", company: "UnitedHealth Group", title: "CEO" },
  { name: "Tim Cook", company: "Apple", title: "CEO" },
  { name: "David Joyner", company: "CVS Health", title: "President and CEO" },
  { name: "Warren Buffett", company: "Berkshire Hathaway", title: "Chairman and CEO" },
  { name: "Sundar Pichai", company: "Alphabet", title: "CEO" },
  { name: "Darren Woods", company: "Exxon Mobil", title: "Chairman and CEO" },
  { name: "Brian Tyler", company: "McKesson", title: "CEO" },
  { name: "Robert Mauch", company: "Cencora", title: "President and CEO" },
  { name: "Jamie Dimon", company: "JPMorgan Chase", title: "Chairman and CEO" },
  { name: "Ron Vachris", company: "Costco Wholesale", title: "President and CEO" },
  { name: "David Cordani", company: "Cigna Group", title: "Chairman and CEO" },
  { name: "Satya Nadella", company: "Microsoft", title: "Chairman and CEO" },
  { name: "Jason Hollar", company: "Cardinal Health", title: "CEO" },
  { name: "Mike Wirth", company: "Chevron", title: "Chairman and CEO" },
  { name: "Brian Moynihan", company: "Bank of America", title: "Chairman and CEO" },
  { name: "Mary Barra", company: "General Motors", title: "Chair and CEO" },
  { name: "Jim Farley", company: "Ford Motor", title: "President and CEO" },
  { name: "Gail Boudreaux", company: "Elevance Health", title: "President and CEO" },
  { name: "Jane Fraser", company: "Citigroup", title: "CEO" },
  { name: "Mark Zuckerberg", company: "Meta Platforms", title: "Chairman and CEO" },
  { name: "Sarah London", company: "Centene", title: "CEO" },
  { name: "Ted Decker", company: "Home Depot", title: "Chair, President and CEO" },
  { name: "Priscilla Almodovar", company: "Fannie Mae", title: "President and CEO" },
  { name: "Tim Wentworth", company: "Walgreens Boots Alliance", title: "CEO" },
  { name: "Ron Sargent", company: "Kroger", title: "CEO" },
  { name: "Mark Lashier", company: "Phillips 66", title: "Chairman and CEO" },
  { name: "Maryann Mannen", company: "Marathon Petroleum", title: "President and CEO" },
  { name: "Hans Vestberg", company: "Verizon Communications", title: "Chairman and CEO" },
  { name: "Jensen Huang", company: "NVIDIA", title: "Founder, President and CEO" },
  { name: "David Solomon", company: "Goldman Sachs", title: "Chairman and CEO" },
  { name: "Charles Scharf", company: "Wells Fargo", title: "CEO and President" },
  { name: "Lane Riggs", company: "Valero Energy", title: "CEO" },
  { name: "Brian Roberts", company: "Comcast", title: "Chairman and CEO" },
  { name: "John Stankey", company: "AT&T", title: "CEO" },
  { name: "James Rechtin", company: "Humana", title: "President and CEO" },
  { name: "Ted Pick", company: "Morgan Stanley", title: "Chairman and CEO" },
  { name: "Brian Cornell", company: "Target", title: "Chair and CEO" },
  { name: "Elon Musk", company: "Tesla", title: "CEO" },
  { name: "Michael Dell", company: "Dell Technologies", title: "Chairman and CEO" },
  { name: "Ramon Laguarta", company: "PepsiCo", title: "Chairman and CEO" },
  { name: "Bob Iger", company: "Walt Disney", title: "CEO" },
  { name: "Carol Tomé", company: "UPS", title: "CEO" },
  { name: "Joaquin Duato", company: "Johnson & Johnson", title: "Chairman and CEO" },
  { name: "Raj Subramaniam", company: "FedEx", title: "President and CEO" },
  { name: "Jon Moeller", company: "Procter & Gamble", title: "Chairman, President and CEO" },
  { name: "Arvind Krishna", company: "IBM", title: "Chairman and CEO" },
  { name: "Michael Miebach", company: "Mastercard", title: "CEO" },
  { name: "Ryan McInerney", company: "Visa", title: "CEO" },
  { name: "Marc Benioff", company: "Salesforce", title: "Chair and CEO" },
  { name: "Ed Bastian", company: "Delta Air Lines", title: "CEO" },
  { name: "Marvin Ellison", company: "Lowe's", title: "Chairman and CEO" },
  { name: "Stephen Squeri", company: "American Express", title: "Chairman and CEO" },
  { name: "Kelly Ortberg", company: "Boeing", title: "President and CEO" },
  { name: "Vimal Kapur", company: "Honeywell", title: "Chairman and CEO" },
  { name: "James Quincey", company: "Coca-Cola", title: "Chairman and CEO" },
  { name: "Robert Ford", company: "Abbott Laboratories", title: "Chairman and CEO" },
  { name: "Albert Bourla", company: "Pfizer", title: "Chairman and CEO" },
  { name: "Lisa Su", company: "AMD", title: "Chair and CEO" },
  { name: "Cristiano Amon", company: "Qualcomm", title: "President and CEO" },
  { name: "Pat Gelsinger", company: "Intel", title: "CEO" },
  { name: "Safra Catz", company: "Oracle", title: "CEO" },
  { name: "Larry Ellison", company: "Oracle", title: "Chairman and CTO" },
  { name: "Shantanu Narayen", company: "Adobe", title: "Chair and CEO" },
  { name: "Daniel Zhang", company: "Alibaba Group", title: "Former Chairman and CEO" },
  { name: "Eddie Wu", company: "Alibaba Group", title: "CEO" },
  { name: "Fidji Simo", company: "Instacart", title: "CEO" },
  { name: "Brian Chesky", company: "Airbnb", title: "CEO and Co-founder" },
  { name: "Daniel Ek", company: "Spotify", title: "CEO and Co-founder" },
  { name: "Patrick Collison", company: "Stripe", title: "CEO and Co-founder" },
  { name: "John Collison", company: "Stripe", title: "President and Co-founder" },
  { name: "Tobias Lütke", company: "Shopify", title: "CEO" },
  { name: "Emilie Choi", company: "Coinbase", title: "President and COO" },
  { name: "Brian Armstrong", company: "Coinbase", title: "CEO and Co-founder" },
  { name: "Vladimir Tenev", company: "Robinhood Markets", title: "CEO and Co-founder" },
  { name: "Baiju Bhatt", company: "Robinhood Markets", title: "Co-founder" },
  { name: "Adam Selipsi", company: "Amazon Web Services", title: "CEO" },
  { name: "Amy Hood", company: "Microsoft", title: "CFO" },
  { name: "Ruth Porat", company: "Alphabet", title: "President and Chief Investment Officer" },
  { name: "Susan Wojcicki", company: "YouTube", title: "Former CEO" },
  { name: "Neal Mohan", company: "YouTube", title: "CEO" },
  { name: "Linda Yaccarino", company: "X", title: "CEO" },
  { name: "Evan Spiegel", company: "Snap", title: "CEO and Co-founder" },
  { name: "Bobby Kotick", company: "Activision Blizzard", title: "Former CEO" },
  { name: "Phil Spencer", company: "Microsoft Gaming", title: "CEO" },
  { name: "Andrew Wilson", company: "Electronic Arts", title: "CEO" },
  { name: "Strauss Zelnick", company: "Take-Two Interactive", title: "Chairman and CEO" },
  { name: "Reed Hastings", company: "Netflix", title: "Co-founder and Executive Chairman" },
  { name: "Ted Sarandos", company: "Netflix", title: "Co-CEO" },
  { name: "Greg Peters", company: "Netflix", title: "Co-CEO" },
  { name: "Dana Walden", company: "Disney Entertainment Television", title: "Co-Chairman" },
  { name: "Alan Bergman", company: "Disney Studios Content", title: "Co-Chairman" },
  { name: "David Zaslav", company: "Warner Bros. Discovery", title: "President and CEO" },
  { name: "Brian Roberts", company: "NBCUniversal", title: "Chairman and CEO of Comcast" },
  { name: "Mike Cavanagh", company: "Comcast", title: "President" },
  { name: "Gina Raimondo", company: "U.S. Department of Commerce", title: "Former Secretary of Commerce" },
  { name: "Kathy Wylde", company: "Partnership for New York City", title: "President and CEO" },
  { name: "Julie Sweet", company: "Accenture", title: "Chair and CEO" },
  { name: "Thierry Breton", company: "European Commission", title: "Former Commissioner" },
  { name: "Christian Klein", company: "SAP", title: "CEO" },
  { name: "Oliver Blume", company: "Volkswagen", title: "CEO" },
  { name: "Carlos Tavares", company: "Stellantis", title: "Former CEO" },
  { name: "John Elkann", company: "Exor", title: "Chairman" },
  { name: "Luca de Meo", company: "Renault", title: "CEO" },
  { name: "Oliver Zipse", company: "BMW", title: "Chairman of the Board of Management" },
  { name: "Ola Källenius", company: "Mercedes-Benz Group", title: "Chairman of the Board of Management" },
  { name: "Jim Farley", company: "Ford", title: "President and CEO" },
  { name: "Akio Toyoda", company: "Toyota Motor", title: "Chairman" },
  { name: "Koji Sato", company: "Toyota Motor", title: "President and CEO" },
  { name: "Makoto Uchida", company: "Nissan Motor", title: "CEO" },
  { name: "Toshihiro Mibe", company: "Honda Motor", title: "President and CEO" },
  { name: "Jim Rowan", company: "Volvo Cars", title: "CEO" },
  { name: "Henrik Fisker", company: "Fisker", title: "Former CEO" },
  { name: "RJ Scaringe", company: "Rivian", title: "Founder and CEO" },
  { name: "Peter Rawlinson", company: "Lucid Motors", title: "CEO and CTO" },
  { name: "Mary Barra", company: "GM", title: "Chair and CEO" },
  { name: "Jon Gray", company: "Blackstone", title: "President and COO" },
  { name: "Stephen Schwarzman", company: "Blackstone", title: "Chairman and CEO" },
  { name: "Jonathan Gray", company: "Blackstone", title: "President and COO" },
  { name: "Larry Fink", company: "BlackRock", title: "Chairman and CEO" },
  { name: "Rob Kapito", company: "BlackRock", title: "President" },
  { name: "Jane Fraser", company: "Citi", title: "CEO" },
  { name: "Charles Scharf", company: "Wells Fargo & Company", title: "CEO" },
  { name: "Bill Winters", company: "Standard Chartered", title: "Group Chief Executive" },
  { name: "Sergio Ermotti", company: "UBS", title: "Group CEO" },
  { name: "Christian Sewing", company: "Deutsche Bank", title: "CEO" },
  { name: "Noël Quinn", company: "HSBC", title: "Former Group Chief Executive" },
  { name: "Georges Elhedery", company: "HSBC", title: "Group CEO" },
  { name: "Ana Botín", company: "Banco Santander", title: "Executive Chair" },
  { name: "Carlos Torres Vila", company: "BBVA", title: "Group Executive Chairman" },
  { name: "Ralph Hamers", company: "UBS", title: "Former Group CEO" },
  { name: "Thasunda Brown Duckett", company: "TIAA", title: "President and CEO" },
  { name: "Deanna Strable-Soethout", company: "Principal Financial Group", title: "President and CEO" },
  { name: "Kecia Steelman", company: "Ulta Beauty", title: "CEO" },
  { name: "Shelley Simpson", company: "J.B. Hunt Transport", title: "President and CEO" },
  { name: "Gunjan Kedia", company: "U.S. Bancorp", title: "President and CEO" },
  { name: "Jennifer Witz", company: "SiriusXM", title: "CEO" },
  { name: "Kathleen Quirk", company: "Freeport-McMoRan", title: "President and CEO" },
  { name: "Toni Townes-Whitley", company: "SAIC", title: "CEO" },
  { name: "Corie Barry", company: "Best Buy", title: "CEO" },
  { name: "Karen Lynch", company: "CVS Health", title: "Former CEO" },
  { name: "Rosalind Brewer", company: "Walgreens Boots Alliance", title: "Former CEO" },
  { name: "Adena Friedman", company: "Nasdaq", title: "Chair and CEO" },
  { name: "Jeffrey Sprecher", company: "Intercontinental Exchange", title: "Chairman and CEO" },
  { name: "Terrence Duffy", company: "CME Group", title: "Chairman and CEO" },
  { name: "Blaise Judja-Sato", company: "Visa", title: "Executive Leader" },
  { name: "Kristin Peck", company: "Zoetis", title: "CEO" },
  { name: "Emma Walmsley", company: "GSK", title: "CEO" },
  { name: "Pascal Soriot", company: "AstraZeneca", title: "CEO" },
  { name: "Christophe Weber", company: "Takeda Pharmaceutical", title: "President and CEO" },
  { name: "Robert Davis", company: "Merck", title: "Chairman and CEO" },
  { name: "Chris Viehbacher", company: "Biogen", title: "President and CEO" },
  { name: "Michel Vounatsos", company: "Biogen", title: "Former CEO" },
  { name: "Paul Hudson", company: "Sanofi", title: "CEO" },
  { name: "Giovanni Caforio", company: "Bristol Myers Squibb", title: "Former CEO" },
  { name: "Christopher Boerner", company: "Bristol Myers Squibb", title: "CEO" },
  { name: "Daniel O'Day", company: "Gilead Sciences", title: "Chairman and CEO" },
  { name: "Jennifer Taubert", company: "Johnson & Johnson", title: "EVP, Worldwide Chairman, Pharmaceuticals" },
  { name: "Alex Gorsky", company: "Johnson & Johnson", title: "Former Chairman and CEO" },
  { name: "Reshma Kewalramani", company: "Vertex Pharmaceuticals", title: "CEO and President" },
  { name: "Michel Vounatsos", company: "Moderna", title: "Board / industry leader" },
  { name: "Stéphane Bancel", company: "Moderna", title: "CEO" },
  { name: "Ugur Sahin", company: "BioNTech", title: "CEO and Co-founder" },
  { name: "Özlem Türeci", company: "BioNTech", title: "CMO and Co-founder" },
  { name: "George Scangos", company: "Vir Biotechnology", title: "Former CEO" },
  { name: "Michelle Hooper", company: "The Directors' Council", title: "Managing Partner" },
  { name: "Indra Nooyi", company: "PepsiCo", title: "Former Chairman and CEO" },
  { name: "Ginni Rometty", company: "IBM", title: "Former Chairman and CEO" },
  { name: "Ursula Burns", company: "Xerox", title: "Former Chairman and CEO" },
  { name: "Meg Whitman", company: "Hewlett Packard Enterprise", title: "Former CEO" },
  { name: "Antonio Neri", company: "Hewlett Packard Enterprise", title: "President and CEO" },
  { name: "Enrique Lores", company: "HP Inc.", title: "President and CEO" },
  { name: "Chuck Robbins", company: "Cisco", title: "Chair and CEO" },
  { name: "Gary Steele", company: "Splunk", title: "Former CEO" },
  { name: "Bill McDermott", company: "ServiceNow", title: "Chairman and CEO" },
  { name: "Aneel Bhusri", company: "Workday", title: "Co-founder and Executive Chair" },
  { name: "Carl Eschenbach", company: "Workday", title: "CEO" },
  { name: "Arianna Huffington", company: "Thrive Global", title: "Founder and CEO" },
  { name: "Whitney Wolfe Herd", company: "Bumble", title: "Founder and Executive Chair" },
  { name: "Lidiane Jones", company: "Bumble", title: "CEO" },
  { name: "Bumble founder", company: "Bumble", title: "Founder" },
  { name: "Dara Khosrowshahi", company: "Uber", title: "CEO" },
  { name: "Logan Green", company: "Lyft", title: "Co-founder" },
  { name: "David Risher", company: "Lyft", title: "CEO" },
  { name: "John Zimmer", company: "Lyft", title: "Co-founder" },
  { name: "Tony Xu", company: "DoorDash", title: "CEO and Co-founder" },
  { name: "Andy Fang", company: "DoorDash", title: "Co-founder" },
  { name: "Stanley Tang", company: "DoorDash", title: "Co-founder" },
  { name: "Drew Houston", company: "Dropbox", title: "CEO and Co-founder" },
  { name: "Arash Ferdowsi", company: "Dropbox", title: "Co-founder" },
  { name: "Stewart Butterfield", company: "Slack", title: "Co-founder" },
  { name: "Eric Yuan", company: "Zoom Video Communications", title: "Founder and CEO" },
  { name: "Jeff Weiner", company: "LinkedIn", title: "Executive Chairman" },
  { name: "Ryan Roslansky", company: "LinkedIn", title: "CEO" },
  { name: "Satya Nadella", company: "LinkedIn", title: "Microsoft CEO (parent)" },
  { name: "Parag Agrawal", company: "Twitter", title: "Former CEO" },
  { name: "Jack Dorsey", company: "Block", title: "Block Head / Co-founder" },
  { name: "Amrita Ahuja", company: "Block", title: "CFO and COO" },
  { name: "Roelof Botha", company: "Sequoia Capital", title: "Managing Partner" },
  { name: "Alfred Lin", company: "Sequoia Capital", title: "Partner" },
  { name: "Mary Meeker", company: "Bond Capital", title: "General Partner" },
  { name: "Marc Andreessen", company: "Andreessen Horowitz", title: "Co-founder and General Partner" },
  { name: "Ben Horowitz", company: "Andreessen Horowitz", title: "Co-founder and General Partner" },
  { name: "Reid Hoffman", company: "Greylock Partners", title: "Partner" },
  { name: "Peter Thiel", company: "Founders Fund", title: "Partner" },
  { name: "Keith Rabois", company: "Khosla Ventures", title: "Managing Director" },
  { name: "Vinod Khosla", company: "Khosla Ventures", title: "Founder" },
  { name: "Bill Gates", company: "Breakthrough Energy", title: "Founder" },
  { name: "Melinda French Gates", company: "Pivotal Ventures", title: "Founder" },
  { name: "MacKenzie Scott", company: "Yield Giving", title: "Philanthropist" },
  { name: "Laurene Powell Jobs", company: "Emerson Collective", title: "Founder and President" },
  { name: "Sheryl Sandberg", company: "LeanIn.Org", title: "Founder" },
  { name: "Susan Wojcicki", company: "YouTube", title: "Former CEO" },
  { name: "Padmasree Warrior", company: "Fable Group", title: "Founder and CEO" },
  { name: "Tracy Young", company: "PlanGrid", title: "Co-founder" },
  { name: "Melanie Perkins", company: "Canva", title: "CEO and Co-founder" },
  { name: "Cliff Obrecht", company: "Canva", title: "COO and Co-founder" },
  { name: "Cameron Adams", company: "Canva", title: "CPO and Co-founder" },
  { name: "Dylan Field", company: "Figma", title: "CEO and Co-founder" },
  { name: "Evan Wallace", company: "Figma", title: "Co-founder" },
  { name: "Guillermo Rauch", company: "Vercel", title: "CEO and Founder" },
  { name: "Tom Preston-Werner", company: "GitHub", title: "Co-founder" },
  { name: "Chris Wanstrath", company: "GitHub", title: "Co-founder" },
  { name: "Thomas Dohmke", company: "GitHub", title: "CEO" },
  { name: "Nat Friedman", company: "Microsoft", title: "Former GitHub CEO" },
  { name: "Sam Altman", company: "OpenAI", title: "CEO" },
  { name: "Greg Brockman", company: "OpenAI", title: "President and Co-founder" },
  { name: "Mira Murati", company: "Thinking Machines Lab", title: "CEO" },
  { name: "Dario Amodei", company: "Anthropic", title: "CEO and Co-founder" },
  { name: "Daniela Amodei", company: "Anthropic", title: "President and Co-founder" },
  { name: "Demis Hassabis", company: "Google DeepMind", title: "CEO" },
  { name: "Mustafa Suleyman", company: "Microsoft AI", title: "CEO" },
  { name: "Fei-Fei Li", company: "Stanford University", title: "Professor; AI4ALL Co-founder" },
  { name: "Andrew Ng", company: "DeepLearning.AI", title: "Founder" },
  { name: "Yann LeCun", company: "Meta", title: "Chief AI Scientist" },
  { name: "Jensen Huang", company: "NVIDIA Corporation", title: "Founder and CEO" },
  { name: "Lisa Su", company: "Advanced Micro Devices", title: "Chair and CEO" },
  { name: "Hock Tan", company: "Broadcom", title: "President and CEO" },
  { name: "Sanjay Mehrotra", company: "Micron Technology", title: "President and CEO" },
  { name: "Gelsinger Patrick", company: "Intel Corporation", title: "Former CEO" },
  { name: "Lip-Bu Tan", company: "Intel", title: "CEO" },
  { name: "Cristiano Amon", company: "Qualcomm Incorporated", title: "President and CEO" },
  { name: "Hans Vestberg", company: "Verizon", title: "CEO" },
  { name: "Mike Sievert", company: "T-Mobile US", title: "President and CEO" },
  { name: "José María Álvarez-Pallete", company: "Telefónica", title: "Chairman" },
  { name: "Nick Read", company: "Vodafone", title: "Former CEO" },
  { name: "Margherita Della Valle", company: "Vodafone Group", title: "Group CEO" },
  { name: "Tim Höttges", company: "Deutsche Telekom", title: "CEO" },
  { name: "Pekka Lundmark", company: "Nokia", title: "President and CEO" },
  { name: "Börje Ekholm", company: "Ericsson", title: "President and CEO" },
  { name: "Thierry Breton", company: "Atos", title: "Former CEO" },
  { name: "François-Henri Pinault", company: "Kering", title: "Chairman and CEO" },
  { name: "Bernard Arnault", company: "LVMH", title: "Chairman and CEO" },
  { name: "Alexandre Arnault", company: "LVMH", title: "Executive Vice President" },
  { name: "Delphine Arnault", company: "Christian Dior Couture", title: "Chairman and CEO" },
  { name: "Marco Gobbetti", company: "Salvatore Ferragamo", title: "CEO" },
  { name: "Jonathan Anderson", company: "Dior", title: "Creative Director" },
  { name: "Emma Walmsley", company: "GlaxoSmithKline", title: "CEO" },
  { name: "Albert Bourla", company: "Pfizer Inc.", title: "CEO" },
  { name: "David Ricks", company: "Eli Lilly", title: "Chair and CEO" },
  { name: "Joaquin Duato", company: "J&J", title: "CEO" },
  { name: "Christophe Weber", company: "Takeda", title: "CEO" },
  { name: "Richard Gonzalez", company: "AbbVie", title: "Chairman and CEO" },
  { name: "Robert Ford", company: "Abbott", title: "CEO" },
  { name: "Kevin Lobo", company: "Stryker", title: "Chair and CEO" },
  { name: "Geoff Martha", company: "Medtronic", title: "Chairman and CEO" },
  { name: "Michael Mahoney", company: "Boston Scientific", title: "Chairman and CEO" },
  { name: "Ashley McEvoy", company: "Johnson & Johnson MedTech", title: "EVP" },
  { name: "Joe Jimenez", company: "Advent International", title: "Senior Advisor; former Nestlé CEO" },
  { name: "Mark Schneider", company: "Nestlé", title: "Former CEO" },
  { name: "Laurent Freixe", company: "Nestlé", title: "CEO" },
  { name: "James Quincey", company: "The Coca-Cola Company", title: "Chairman and CEO" },
  { name: "Ramon Laguarta", company: "PepsiCo Inc.", title: "CEO" },
  { name: "Sean Connolly", company: "Conagra Brands", title: "President and CEO" },
  { name: "Jeff Harmening", company: "General Mills", title: "Chairman and CEO" },
  { name: "Carlos Abrams-Rivera", company: "Kraft Heinz", title: "CEO" },
  { name: "Dirk Van de Put", company: "Mondelez International", title: "Chair and CEO" },
  { name: "Steve Cahillane", company: "Kellanova", title: "Chairman and CEO" },
  { name: "Gary Pilnick", company: "WK Kellogg Co", title: "CEO" },
  { name: "Brian Niccol", company: "Starbucks", title: "Chairman and CEO" },
  { name: "Laxman Narasimhan", company: "Starbucks", title: "Former CEO" },
  { name: "Chris Kempczinski", company: "McDonald's", title: "President and CEO" },
  { name: "Josh Kobza", company: "Restaurant Brands International", title: "CEO" },
  { name: "Dave Calhoun", company: "Boeing", title: "Former CEO" },
  { name: "Guillaume Faury", company: "Airbus", title: "CEO" },
  { name: "David Calhoun", company: "Boeing Company", title: "Former President and CEO" },
  { name: "Greg Hayes", company: "RTX", title: "Executive Chairman" },
  { name: "Chris Calio", company: "RTX", title: "President and CEO" },
  { name: "Jim Taiclet", company: "Lockheed Martin", title: "Chairman, President and CEO" },
  { name: "Kathy Warden", company: "Northrop Grumman", title: "Chair, CEO and President" },
  { name: "Phebe Novakovic", company: "General Dynamics", title: "Chair and CEO" },
  { name: "Abney Benjamin", company: "GE Aerospace", title: "Leadership" },
  { name: "H. Lawrence Culp Jr.", company: "GE Aerospace", title: "Chairman and CEO" },
  { name: "Scott Strazik", company: "GE Vernova", title: "CEO" },
  { name: "John Flannery", company: "General Electric", title: "Former CEO" },
  { name: "Jim Fitterling", company: "Dow", title: "Chair and CEO" },
  { name: "Jim Collins", company: "Corteva", title: "CEO" },
  { name: "Edward Breen", company: "DuPont", title: "Executive Chairman" },
  { name: "Lori Koch", company: "DuPont", title: "CEO" },
  { name: "Jim Fitterling", company: "Dow Inc.", title: "CEO" },
  { name: "Seifi Ghasemi", company: "Air Products", title: "Chairman, President and CEO" },
  { name: "Sanjiv Lamba", company: "Linde", title: "CEO" },
  { name: "Hugh Grant", company: "Monsanto", title: "Former Chairman and CEO" },
  { name: "Brett Biggs", company: "Walmart", title: "Former CFO" },
  { name: "John David Rainey", company: "Walmart", title: "CFO" },
  { name: "Brian Olsavsky", company: "Amazon", title: "CFO" },
  { name: "Luca Maestri", company: "Apple", title: "CFO" },
  { name: "Kate Johnson", company: "Lumen Technologies", title: "President and CEO" },
  { name: "Jeff Storey", company: "Lumen Technologies", title: "Former CEO" },
  { name: "Chuck Robbins", company: "Cisco Systems", title: "Chair and CEO" },
  { name: "Rami Rahim", company: "Juniper Networks", title: "CEO" },
  { name: "Nikesh Arora", company: "Palo Alto Networks", title: "Chairman and CEO" },
  { name: "Jay Chaudhry", company: "Zscaler", title: "CEO and Chairman" },
  { name: "George Kurtz", company: "CrowdStrike", title: "CEO and Co-founder" },
  { name: "Kevin Mandia", company: "Google Cloud / Mandiant", title: "Founder" },
  { name: "Matthew Prince", company: "Cloudflare", title: "CEO and Co-founder" },
  { name: "Michelle Zatlyn", company: "Cloudflare", title: "President and Co-founder" },
  { name: "Frank Slootman", company: "Snowflake", title: "Former CEO" },
  { name: "Sridhar Ramaswamy", company: "Snowflake", title: "CEO" },
  { name: "Ali Ghodsi", company: "Databricks", title: "CEO and Co-founder" },
  { name: "Ion Stoica", company: "Databricks", title: "Co-founder and Executive Chairman" },
  { name: "Matei Zaharia", company: "Databricks", title: "Co-founder and Chief Technologist" },
  { name: "Aaron Levie", company: "Box", title: "CEO and Co-founder" },
  { name: "Andrew Burton", company: "Datadog", title: "COO" },
  { name: "Olivier Pomel", company: "Datadog", title: "CEO and Co-founder" },
  { name: "Alexis Lê-Quôc", company: "Datadog", title: "CTO and Co-founder" },
  { name: "Scott Farquhar", company: "Atlassian", title: "Co-founder" },
  { name: "Mike Cannon-Brookes", company: "Atlassian", title: "Co-founder and CEO" },
  { name: "Anil Dash", company: "Glitch", title: "CEO" },
  { name: "Stewart Butterfield", company: "Tiny Speck / Slack", title: "Co-founder" },
  { name: "Stewart Butterfield", company: "Flickr", title: "Co-founder" },
  { name: "Biz Stone", company: "X / Twitter", title: "Co-founder" },
  { name: "Ev Williams", company: "Medium", title: "CEO and Co-founder" },
  { name: "Noah Glass", company: "Odeo", title: "Co-founder" },
  { name: "Kevin Systrom", company: "Instagram", title: "Co-founder" },
  { name: "Mike Krieger", company: "Instagram", title: "Co-founder" },
  { name: "Adam Mosseri", company: "Instagram", title: "Head of Instagram" },
  { name: "Shou Chew", company: "TikTok", title: "CEO" },
  { name: "Zhang Yiming", company: "ByteDance", title: "Founder" },
  { name: "Liang Rubo", company: "ByteDance", title: "CEO" },
  { name: "Tencent Pony Ma", company: "Tencent", title: "Founder" },
  { name: "Ma Huateng", company: "Tencent", title: "Chairman and CEO" },
  { name: "Lei Jun", company: "Xiaomi", title: "Founder, Chairman and CEO" },
  { name: "Ren Zhengfei", company: "Huawei", title: "Founder" },
  { name: "Eric Xu", company: "Huawei", title: "Deputy Chairman" },
  { name: "Young Liu", company: "Foxconn", title: "Chairman" },
  { name: "Terry Gou", company: "Foxconn", title: "Founder" },
  { name: "Jensen Huang", company: "NVIDIA", title: "CEO" },
  { name: "Iris Patel", company: "Applied Materials", title: "Leadership" },
  { name: "Gary Dickerson", company: "Applied Materials", title: "President and CEO" },
  { name: "Rick Wallace", company: "KLA", title: "CEO" },
  { name: "Patrick Wood", company: "Lam Research", title: "CEO / leadership" },
  { name: "Tim Archer", company: "Lam Research", title: "President and CEO" },
  { name: "C.C. Wei", company: "TSMC", title: "CEO" },
  { name: "Mark Liu", company: "TSMC", title: "Former Chairman" },
  { name: "Morris Chang", company: "TSMC", title: "Founder" },
  { name: "Pat Gelsinger", company: "Gelsinger Ventures", title: "Former Intel CEO" },
  { name: "Craig Barrett", company: "Intel", title: "Former CEO" },
  { name: "Paul Otellini", company: "Intel", title: "Former CEO" },
  { name: "Brian Krzanich", company: "Intel", title: "Former CEO" },
  { name: "Bob Swan", company: "Intel", title: "Former CEO" },
  { name: "Omar Ishrak", company: "Medtronic", title: "Former Chairman and CEO" },
  { name: "Geoff Martha", company: "Medtronic plc", title: "CEO" },
  { name: "Alex Gorsky", company: "J&J", title: "Former CEO" },
  { name: "William Perez", company: "Nike", title: "Former CEO" },
  { name: "John Donahoe", company: "Nike", title: "President and CEO" },
  { name: "Elliott Hill", company: "Nike", title: "President and CEO" },
  { name: "Chip Bergh", company: "Levi Strauss & Co.", title: "Former President and CEO" },
  { name: "Michelle Gass", company: "Levi Strauss & Co.", title: "President and CEO" },
  { name: "Patrice Louvet", company: "Ralph Lauren", title: "President and CEO" },
  { name: "Marco Gobbetti", company: "Salvatore Ferragamo", title: "CEO" },
  { name: "Hubert Joly", company: "Best Buy", title: "Former Chairman and CEO" },
  { name: "Corie Barry", company: "Best Buy Co.", title: "CEO" },
  { name: "Ed Bastian", company: "Delta", title: "CEO" },
  { name: "Robert Isom", company: "American Airlines", title: "CEO" },
  { name: "Scott Kirby", company: "United Airlines", title: "CEO" },
  { name: "Bob Jordan", company: "Southwest Airlines", title: "CEO" },
  { name: "David Calhoun", company: "Boeing", title: "Former CEO" },
  { name: "Dave Calhoun", company: "The Boeing Company", title: "Former CEO" },
  { name: "Oscar Munoz", company: "United Airlines", title: "Former CEO" },
  { name: "Gary Kelly", company: "Southwest Airlines", title: "Former CEO" },
  { name: "Doug Parker", company: "American Airlines", title: "Former Chairman and CEO" },
  { name: "Richard Branson", company: "Virgin Group", title: "Founder" },
  { name: "Shai Agassi", company: "Better Place", title: "Former CEO" },
  { name: "Travis Kalanick", company: "Uber", title: "Co-founder" },
  { name: "Garrett Camp", company: "Uber", title: "Co-founder" },
  { name: "Ryan Graves", company: "Uber", title: "Former SVP Global Operations" },
  { name: "Tony West", company: "Uber", title: "Chief Legal Officer" },
  { name: "Jill Hazelbaker", company: "Uber", title: "SVP Marketing and Public Affairs" },
  { name: "Andrew Macdonald", company: "Uber", title: "SVP and Mobility COO" },
  { name: "Prashanth Mahendra-Rajah", company: "Uber", title: "CFO" },
  { name: "Nikki Krishnamurthy", company: "Uber", title: "Chief People Officer" },
  { name: "Barrett Kupplick", company: "DoorDash", title: "Leadership" },
  { name: "Prabir Adarkar", company: "DoorDash", title: "President and COO" },
  { name: "Ravi Inukonda", company: "DoorDash", title: "CFO" },
  { name: "Tia Sherringham", company: "DoorDash", title: "General Counsel" },
  { name: "Andy Fang", company: "DoorDash Inc.", title: "Co-founder and CTO" },
  { name: "Stanley Tang", company: "DoorDash Inc.", title: "Co-founder" },
  { name: "Tony Xu", company: "DoorDash Inc.", title: "CEO" },
  { name: "Brian Chesky", company: "Airbnb Inc.", title: "CEO" },
  { name: "Joe Gebbia", company: "Airbnb", title: "Co-founder" },
  { name: "Nathan Blecharczyk", company: "Airbnb", title: "Co-founder and Chief Strategy Officer" },
  { name: "Dave Stephenson", company: "Airbnb", title: "CFO" },
  { name: "Aristotle Balogh", company: "Airbnb", title: "CTO" },
  { name: "Catherine Powell", company: "Airbnb", title: "Former Head of Hosting" },
  { name: "Belinda Johnson", company: "Airbnb", title: "Former COO" },
  { name: "Daniel Ek", company: "Spotify Technology", title: "CEO" },
  { name: "Martin Lorentzon", company: "Spotify", title: "Co-founder" },
  { name: "Gustav Söderström", company: "Spotify", title: "Co-President and CPO/CTO" },
  { name: "Alex Norström", company: "Spotify", title: "Co-President and CCO" },
  { name: "Dawn Ostroff", company: "Spotify", title: "Former Chief Content Officer" },
  { name: "Judy Levin", company: "Spotify", title: "Leadership" },
  { name: "Susan Wojcicki", company: "YouTube LLC", title: "Former CEO" },
  { name: "Neal Mohan", company: "YouTube LLC", title: "CEO" },
  { name: "Robert Kyncl", company: "Warner Music Group", title: "CEO" },
  { name: "Lucian Grainge", company: "Universal Music Group", title: "Chairman and CEO" },
  { name: "Rob Stringer", company: "Sony Music Entertainment", title: "Chairman" },
  { name: "Jon Platt", company: "Universal Music Publishing Group", title: "Chairman and CEO" },
  { name: "Irving Azoff", company: "Oak View Group / Azoff Company", title: "Chairman" },
  { name: "Live Nation Michael Rapino", company: "Live Nation Entertainment", title: "CEO" },
  { name: "Michael Rapino", company: "Live Nation Entertainment", title: "President and CEO" },
  { name: "Joe Berchtold", company: "Live Nation", title: "President and CFO" },
  { name: "Arthur Fogel", company: "Live Nation", title: "Chairman of Global Music" },
  { name: "Jay Marciano", company: "AEG Presents", title: "Chairman and CEO" },
  { name: "Dan Reed", company: "AEG", title: "Leadership" },
  { name: "Philip Anschutz", company: "The Anschutz Corporation", title: "Founder" },
  { name: "John Malone", company: "Liberty Media", title: "Chairman" },
  { name: "Greg Maffei", company: "Liberty Media", title: "President and CEO" },
  { name: "Chase Carey", company: "Formula One Group", title: "Former Chairman" },
  { name: "Stefano Domenicali", company: "Formula 1", title: "President and CEO" },
  { name: "Mohammed Ben Sulayem", company: "FIA", title: "President" },
  { name: "Roger Penske", company: "Penske Corporation", title: "Founder and Chairman" },
  { name: "Jim Farley", company: "Ford Motor Company", title: "CEO" },
  { name: "Joe Hinrichs", company: "Ford", title: "Former President, Automotive" },
  { name: "Jim Hackett", company: "Ford", title: "Former CEO" },
  { name: "Mark Fields", company: "Ford", title: "Former CEO" },
  { name: "Alan Mulally", company: "Ford", title: "Former CEO" },
  { name: "Bill Ford", company: "Ford Motor Company", title: "Executive Chairman" },
  { name: "Mary Barra", company: "General Motors Company", title: "CEO" },
  { name: "Mark Reuss", company: "General Motors", title: "President" },
  { name: "Paul Jacobson", company: "General Motors", title: "CFO" },
  { name: "Doug Parks", company: "General Motors", title: "EVP Global Product" },
  { name: "Dan Ammann", company: "General Motors", title: "Former President" },
  { name: "Stephen Girsky", company: "General Motors", title: "Former Vice Chairman" },
  { name: "Akira Marumoto", company: "Honda", title: "Leadership" },
  { name: "Toshihiro Mibe", company: "Honda", title: "CEO" },
  { name: "Makoto Uchida", company: "Nissan", title: "CEO" },
  { name: "Asako Hoshino", company: "Nissan", title: "Leadership" },
  { name: "Carlos Ghosn", company: "Renault-Nissan-Mitsubishi", title: "Former Chairman and CEO" },
  { name: "Hiroto Saikawa", company: "Nissan", title: "Former CEO" },
  { name: "Olivier François", company: "Stellantis", title: "Chief Marketing Officer / Fiat brand CEO" },
  { name: "Carlos Tavares", company: "Stellantis N.V.", title: "Former CEO" },
  { name: "John Elkann", company: "Ferrari / Exor", title: "Chairman" },
  { name: "Benedetto Vigna", company: "Ferrari", title: "CEO" },
  { name: "Oliver Blume", company: "Porsche AG / Volkswagen Group", title: "CEO" },
  { name: "Oliver Zipse", company: "BMW Group", title: "CEO" },
  { name: "Ola Källenius", company: "Mercedes-Benz", title: "CEO" },
  { name: "Markus Duesmann", company: "Audi", title: "Former Chairman" },
  { name: "Gernot Döllner", company: "Audi", title: "CEO" },
  { name: "Thomas Schäfer", company: "Volkswagen Passenger Cars", title: "CEO" },
  { name: "Herbert Diess", company: "Volkswagen", title: "Former CEO" },
  { name: "Matthias Müller", company: "Volkswagen", title: "Former CEO" },
  { name: "Martin Winterkorn", company: "Volkswagen", title: "Former CEO" },
  { name: "Arvind Krishna", company: "International Business Machines", title: "CEO" },
  { name: "Jim Whitehurst", company: "IBM", title: "Former President" },
  { name: "John Kelly", company: "IBM", title: "Former EVP" },
  { name: "Ginni Rometty", company: "International Business Machines", title: "Former CEO" },
  { name: "Samuel Palmisano", company: "IBM", title: "Former CEO" },
  { name: "Louis Gerstner", company: "IBM", title: "Former CEO" },
  { name: "Satya Nadella", company: "Microsoft Corporation", title: "CEO" },
  { name: "Brad Smith", company: "Microsoft", title: "Vice Chair and President" },
  { name: "Amy Hood", company: "Microsoft Corporation", title: "CFO" },
  { name: "Judith Sim", company: "Oracle", title: "Former CMO" },
  { name: "Safra Catz", company: "Oracle Corporation", title: "CEO" },
  { name: "Clay Magouyrk", company: "Oracle", title: "CEO co-lead / cloud leadership" },
  { name: "Mike Sicilia", company: "Oracle", title: "CEO co-lead / industry leadership" },
  { name: "Thomas Kurian", company: "Google Cloud", title: "CEO" },
  { name: "Philipp Schindler", company: "Google", title: "Chief Business Officer" },
  { name: "Prabhakar Raghavan", company: "Google", title: "Chief Technologist" },
  { name: "Kent Walker", company: "Google / Alphabet", title: "President, Global Affairs" },
  { name: "Anat Ashkenazi", company: "Google / Alphabet", title: "CFO" },
  { name: "Ruth Porat", company: "Alphabet Inc.", title: "President and CIO" },
  { name: "Sundar Pichai", company: "Google", title: "CEO" },
  { name: "Sergey Brin", company: "Alphabet", title: "Co-founder" },
  { name: "Larry Page", company: "Alphabet", title: "Co-founder" },
  { name: "Eric Schmidt", company: "Google", title: "Former CEO" },
  { name: "John Hennessy", company: "Alphabet", title: "Chairman" },
  { name: "John Doerr", company: "Kleiner Perkins", title: "Chairman" },
  { name: "Vinod Khosla", company: "Khosla Ventures", title: "Founder" },
  { name: "Mary Meeker", company: "Bond", title: "General Partner" },
  { name: "Bill Gurley", company: "Benchmark", title: "General Partner" },
  { name: "Peter Fenton", company: "Benchmark", title: "General Partner" },
  { name: "Mitch Lasky", company: "Benchmark", title: "General Partner" },
  { name: "Eric Vishria", company: "Benchmark", title: "General Partner" },
  { name: "Sarah Tavel", company: "Benchmark", title: "General Partner" },
  { name: "Chetan Puttagunta", company: "Benchmark", title: "General Partner" },
  { name: "Anjney Midha", company: "a16z", title: "General Partner" },
  { name: "Chris Dixon", company: "Andreessen Horowitz", title: "General Partner" },
  { name: "Scott Kupor", company: "Andreessen Horowitz", title: "Managing Partner" },
  { name: "Andrew Chen", company: "Andreessen Horowitz", title: "General Partner" },
  { name: "Connie Chan", company: "Andreessen Horowitz", title: "General Partner" },
  { name: "David Haber", company: "Andreessen Horowitz", title: "General Partner" },
  { name: "Martin Casado", company: "Andreessen Horowitz", title: "General Partner" },
  { name: "Jeff Jordan", company: "Andreessen Horowitz", title: "General Partner" },
  { name: "Alex Rampell", company: "Andreessen Horowitz", title: "General Partner" },
  { name: "Katherine Boyle", company: "Andreessen Horowitz", title: "General Partner" },
  { name: "David Ulevitch", company: "Andreessen Horowitz", title: "General Partner" },
  { name: "Sriram Krishnan", company: "Andreessen Horowitz", title: "General Partner" },
  { name: "Anish Acharya", company: "Andreessen Horowitz", title: "General Partner" },
  { name: "Jennifer Li", company: "Andreessen Horowitz", title: "General Partner" },
  { name: "David George", company: "Andreessen Horowitz", title: "General Partner" },
  { name: "Ryan Merket", company: "Andreessen Horowitz", title: "Operating Partner" },
];

function slugEmail(name: string, company: string) {
  const local = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ".")
    .replace(/^\.+|\.+$/g, "")
    .slice(0, 40);
  const domain = company
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "")
    .slice(0, 24);
  return `${local}@${domain || "example"}.example`;
}

function fakePhone(i: number) {
  const n = String(1000 + (i % 8900)).padStart(4, "0");
  const area = ["212", "415", "312", "617", "206", "512", "303", "404", "713", "310"][i % 10];
  return `(${area}) 555-${n}`;
}

function daysAgo(i: number) {
  const d = new Date("2026-08-01T12:00:00Z");
  d.setUTCDate(d.getUTCDate() - ((i * 7) % 720));
  return d.toISOString().slice(0, 10);
}

const NOTE_TEMPLATES = [
  "Met at industry conference. Discussed key person coverage for leadership transition planning.",
  "Warm intro from a mutual CPA. Open to buy-sell conversation if ownership change is real.",
  "Prior inbound about executive benefits. Said call after Q2 board cycle.",
  "Public company leadership — verify role still current before outreach. Interested in estate liquidity planning historically.",
  "Referred by center-of-influence. Asked about succession funding options.",
  "Notes from webinar attendance. High-value household; prefers email first then phone.",
  "Follow up on policy window mentioned last year. Company still active in sector news.",
  "Thin file besides public role. Confirm company association before dialing.",
  "Former conversation about deferred comp / executive benefits stalled. Reopen carefully.",
  "Board-level contact path via referral. Mentioned liquidity event timing uncertainty.",
];

function csvEscape(value: string) {
  if (/[",\n]/.test(value)) return `"${value.replace(/"/g, '""')}"`;
  return value;
}

function main() {
  const seen = new Set<string>();
  const unique: Person[] = [];
  for (const p of PEOPLE) {
    const key = `${p.name.toLowerCase()}|${p.company.toLowerCase()}`;
    if (seen.has(key)) continue;
    // Drop obviously bad placeholder rows
    if (/^bumble founder$/i.test(p.name)) continue;
    if (/^tencent pony ma$/i.test(p.name)) continue;
    if (/^live nation michael/i.test(p.name)) continue;
    if (/^gelsinger patrick$/i.test(p.name)) continue;
    if (/^iris patel$/i.test(p.name)) continue;
    if (/^barrett kupplick$/i.test(p.name)) continue;
    if (/^abney benjamin$/i.test(p.name)) continue;
    if (/^judy levin$/i.test(p.name)) continue;
    if (/^dan reed$/i.test(p.name)) continue;
    if (/^blaise judja/i.test(p.name)) continue;
    if (/leadership$/i.test(p.title) && /iris|barrett|abney|akira|asako/i.test(p.name)) continue;
    seen.add(key);
    unique.push(p);
  }

  if (unique.length < 200) {
    throw new Error(`Need at least 200 unique people, got ${unique.length}`);
  }

  const header = [
    "Name",
    "Email",
    "Phone",
    "Company",
    "Title",
    "Segment",
    "Source",
    "Last Touch",
    "Notes",
    "Value",
    "LinkedIn",
  ];

  const rows = unique.map((p, i) => {
    const note = NOTE_TEMPLATES[i % NOTE_TEMPLATES.length]!;
    return [
      p.name,
      slugEmail(p.name, p.company),
      fakePhone(i),
      p.company,
      p.title,
      i % 5 === 0 ? "Public company executive" : "Business decision maker",
      i % 3 === 0 ? "web research" : i % 3 === 1 ? "public leadership page" : "news mention",
      daysAgo(i),
      `${note} [TEST DATA — synthetic phone/email; not for outreach]`,
      i % 4 === 0 ? "High" : i % 4 === 1 ? "Medium" : "",
      "",
    ]
      .map((cell) => csvEscape(String(cell)))
      .join(",");
  });

  const csv = [header.join(","), ...rows].join("\n") + "\n";
  const publicPath = join(process.cwd(), "public", "public-figures-test-book.csv");
  const downloadsPath = join(homedir(), "Downloads", "public-figures-test-book.csv");
  writeFileSync(publicPath, csv, "utf8");
  mkdirSync(join(homedir(), "Downloads"), { recursive: true });
  writeFileSync(downloadsPath, csv, "utf8");

  console.log(`Wrote ${unique.length} rows`);
  console.log(`- ${publicPath}`);
  console.log(`- ${downloadsPath}`);
  console.log("Disclaimer: public figures only; synthetic phones/emails; not for outreach.");
}

main();
